name: bokain_calendar
description: Calendar components for bokain.se
version: 0.0.1
#homepage: https://www.example.com
#author: Patrick <email@example.com>

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular2: "^3.1.0"
  angular_components: "^0.5.2"
  bokain_models:
    path: ../bokain-models/

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
