name: bokain_calendar
description: Calendar components for bokain.se
version: 0.0.1
#homepage: https://www.example.com
#author: Patrick <email@example.com>

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: "^4.0.0-beta"
  angular_components: "^0.6.0-beta"
  angular_router: "^1.0.1"
  bokain_models:
    path: ../bokain-models/

transformers:
- angular
